---
amazon:
  client_id: AMAZON_CLIENT_ID
  client_secret: AMAZON_CLIENT_SECRET
amazon_eks:
  hostname: amazonhostname
  cluster_name: CLUSTER_NAME
  client_id: AMAZON_CLIENT_ID
  client_secret: AMAZON_CLIENT_SECRET
