---
ap-east-1:
  :name: ap-east-1
  :hostname: ec2.ap-east-1.amazonaws.com
  :description: Asia Pacific (Hong Kong)
ap-northeast-1:
  :name: ap-northeast-1
  :hostname: ec2.ap-northeast-1.amazonaws.com
  :description: Asia Pacific (Tokyo)
ap-northeast-2:
  :name: ap-northeast-2
  :hostname: ec2.ap-northeast-2.amazonaws.com
  :description: Asia Pacific (Seoul)
ap-northeast-3:
  :name: ap-northeast-3
  :hostname: ec2.ap-northeast-3.amazonaws.com
  :description: Asia Pacific (Osaka-Local)
ap-south-1:
  :name: ap-south-1
  :hostname: ec2.ap-south-1.amazonaws.com
  :description: Asia Pacific (Mumbai)
ap-southeast-1:
  :name: ap-southeast-1
  :hostname: ec2.ap-southeast-1.amazonaws.com
  :description: Asia Pacific (Singapore)
ap-southeast-2:
  :name: ap-southeast-2
  :hostname: ec2.ap-southeast-2.amazonaws.com
  :description: Asia Pacific (Sydney)
ca-central-1:
  :name: ca-central-1
  :hostname: ec2.ca-central-1.amazonaws.com
  :description: Canada (Central)
eu-central-1:
  :name: eu-central-1
  :hostname: ec2.eu-central-1.amazonaws.com
  :description: EU (Frankfurt)
eu-north-1:
  :name: eu-north-1
  :hostname: ec2.eu-north-1.amazonaws.com
  :description: EU (Stockholm)
eu-south-1:
  :name: eu-south-1
  :hostname: ec2.eu-south-1.amazonaws.com
  :description: EU (Milan)
eu-west-1:
  :name: eu-west-1
  :hostname: ec2.eu-west-1.amazonaws.com
  :description: EU (Ireland)
eu-west-2:
  :name: eu-west-2
  :hostname: ec2.eu-west-2.amazonaws.com
  :description: EU (London)
eu-west-3:
  :name: eu-west-3
  :hostname: ec2.eu-west-3.amazonaws.com
  :description: EU (Paris)
me-south-1:
  :name: me-south-1
  :hostname: ec2.me-south-1.amazonaws.com
  :description: Middle East (Bahrain)
sa-east-1:
  :name: sa-east-1
  :hostname: ec2.sa-east-1.amazonaws.com
  :description: South America (Sao Paulo)
us-east-1:
  :name: us-east-1
  :hostname: ec2.us-east-1.amazonaws.com
  :description: US East (N. Virginia)
us-east-2:
  :name: us-east-2
  :hostname: ec2.us-east-2.amazonaws.com
  :description: US East (Ohio)
us-west-1:
  :name: us-west-1
  :hostname: ec2.us-west-1.amazonaws.com
  :description: US West (N. California)
us-west-2:
  :name: us-west-2
  :hostname: ec2.us-west-2.amazonaws.com
  :description: US West (Oregon)
cn-north-1:
  :name: cn-north-1
  :hostname: ec2.cn-north-1.amazonaws.com.cn
  :description: China (Beijing)
cn-northwest-1:
  :name: cn-northwest-1
  :hostname: ec2.cn-northwest-1.amazonaws.com.cn
  :description: China (Ningxia)
us-gov-east-1:
  :name: us-gov-east-1
  :hostname: ec2.us-gov-east-1.amazonaws.com
  :description: AWS GovCloud (US-East)
us-gov-west-1:
  :name: us-gov-west-1
  :hostname: ec2.us-gov-west-1.amazonaws.com
  :description: AWS GovCloud (US)
